name = "telegram-eghatha-bot"
main = "src/index.ts"
compatibility_date = "2024-03-25"

[triggers]
crons = [
  "0 18 * * *",    # Daily polls (18:00 UTC = 00:00 Riyadh)
  "0 18 * * 5",    # Weekly polls (Friday 18:00 UTC)
]

[vars]
ADMIN_ID = "1406308261"
CHANNEL_ID = "-1002313808274"
BOT_TOKEN = "7904764998:AAGYYu_fXyIsqOh4b6c8Q9HDX-jMg55oQtc"


[[kv_namespaces]]
binding = "POLL_STORE"
id = "7b67f3a964f1422c8d1badb684a276a0"
preview_id = "9878a30cf5f144f4be80c16bec7c6d6f"

[[kv_namespaces]]
binding = "SUBSCRIBED_CHATS_STORE"
id = "67b9832bda4d4d5a8a76a2fb3486ad4c"
preview_id = "0765dd9f807b4abead469e6f10389874"



